title: mobi 格式
description: mobi 格式相关介绍
theme: jekyll-theme-leap-day
show_downloads: true
google_analytics: UA-79883090-5
github: 
  is_project_page: true
  owner_url: http://blog.devhitao.com # 底部拥有者链接
  owner_name: hitao

# Custom 
show_theme_author: false  # Hosted on GitHub Pages &mdash; Theme by geshi.mobi